version: '3.9'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
    # path to the saved data inside the container
      - 'db:/var/lib/postgresql/data'
    networks:
      - passin

  api-pass-in:
    build:
      context: .
      # context: navigate through files where your docker file is, if it is in the same directory as your docker-compose file, the
      # dockerfile: name of dockerfile
    container_name: api-pass-in
    ports:
      - 3001:${POSTGRES_PORT}
    environment:
      #postgres recognizes the api into the same network,
      # so passing @postgres instead of localhost resolves the problem
      - API_BASE_URL=api-pass-in
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/passin
    depends_on:
      - postgres
    networks:
      - passin

networks:
  passin:
    driver: bridge

volumes:
  db: