version: '3.7'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=passin
    networks:
      - passin

  api-pass-in:
    build:
      context: .
      # context: navigate through files where your docker file is, if it is in the same directory as your docker-compose file, the
      # dockerfile: name of dockerfile
    container_name: api-pass-in
    ports:
      - "3001:3333"
    environment:
      #postgres recognizes the api into the same network,
      # so passing @postgres instead of localhost resolves the problem
      - API_BASE_URL=http://localhost:3333
      - DATABASE_URL=postgresql://admin:admin@postgres:3333/passin
    depends_on:
      - postgres
    networks:
      - passin

networks:
  passin:
    driver: bridge
