version: '3.7'

services:
  api-pass-in:
    build:
      context: .
      # context: navigate through files where your docker file is, if it is in the same directory as your docker-compose file, the
      # dockerfile: name of dockerfile
    container_name: api-pass-in
    ports:
      - "3001:3333"
    environment:
      - API_BASE_URL=http://localhost:3333
      - DATABASE_URL=file:./db.sqlite
