apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: ns
data:
  API_BASE_URL: 'http://localhost:3000'
  DATABASE_URL: ''
  POSTGRES_PORT: '3000'
  POSTGRES_USER: 'root'
  POSTGRES_PASSWORD: 'root'
  POSTGRES_DB: 'my-db'
