apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-app-deployment
  labels:
    app: my-app


spec:
  replicas: 5
# resolve internally by the label 
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: ...
          envFrom: 
            - configMapRef:
                name: app-name-configmap
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          ports:
          - containerPort: 3000