name: CI

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - master

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate sha
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "SHA=${SHA}" >> $GITHUB_OUTPUT

    - name: Build docker image
      run: docker build -t alenerick/nlw.service.passin:${{ steps.generate_sha.outputs.sha }} .

    - name: Log into the container registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name:
      run: |
        docker push alenerick/nlw.service.passin:${{ steps.generate_sha.outputs.sha }}
        docker tag alenerick/nlw.service.passin:${{ steps.generate_sha.outputs.sha }} alenerick/nlw.service.passin:latest
        docker push alenerick/nlw.service.passin:latest

    - name: YAML Update Action
      uses: fjogeleit/yaml-update-action@main
      with:
        # token: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
        branch: main
        valueFile: 'deploy/values.yaml'
        propertyPath: 'image.tag'
        value: ${{ steps.generate_sha.outputs.sha }}
        commitChange: true
        message: 'new: Updated tag in values helm'