name: CI

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - master

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate sha
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "SHA=${SHA}" >> $GITHUB_OUTPUT

    - name: Build docker image
      run: docker build -t alenerick/nlw.service.passin:${{ steps.generate_sha.outputs.sha }} .

    - name: Log into the container registry
      run: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name:
      run: |
        docker push alenerick/nlw.service.passin:${{ steps.generate_sha.outputs.sha }}